### ISSUE TITLE
Invalid group error

### ISSUE THREAD

**Issue by KendallPark** [boxen/our-boxen#235]
``` sh
Error: Invalid group: 10000
Error: /Stage[main]/Nvm/File[/opt/boxen/bin/node-waf]/ensure: change from absent to link failed: Invalid group: 10000
Error: Invalid group: 10000
Error: /Stage[main]/Nvm/File[/opt/boxen/bin/npm]/ensure: change from absent to link failed: Invalid group: 10000
```

Homebrew just updated ~2 hours ago and I've started getting this error while running boxen. Is this related to https://github.com/boxen/our-boxen/issues/172 ?

More errors:

``` sh
Error: Invalid group: 10000
Error: /Stage[main]/Nvm/File[/opt/boxen/bin/node]/ensure: change from absent to link failed: Invalid group: 10000

Error: Invalid group: 10000
Error: /Stage[main]/Git/File[/opt/boxen/bin/boxen-git-credential]/ensure: change from absent to link failed: Invalid group: 10000
```

**Comment by lstoll** [comment]
FWIW this seems to be a bug in puppet, I've reported it here: https://tickets.puppetlabs.com/browse/PUP-5047

This fix here: https://github.com/lstoll/puppet/commit/53efaffcb45fc165b12685f2085c1f732e4bfb9b seems to validate it. If I ever get anywhere, I'll open a PR to revert the hack in #581 and bump puppet.

**Comment by jonstorer** [comment]
I'm a bit late to the game, but I'm hitting this now. And FWIW, this is still an issue. Half of our macs are on a windows domain and they fail. So I'm using the hack above, which is a hack, not a fix, so I'm not sure why this is closed.

Anyway, what if we just used the user's main group? `id -gn` will give the group name, so why not use it? This script assumes the group is `staff`, but we could just ask the system.

Thoughts?
