### ISSUE TITLE
puppet-unarchiver

### ISSUE THREAD

**Issue by dieterdemeyer** [boxen/our-boxen#328]
https://github.com/dieterdemeyer/puppet-unarchiver

**Comment by seanknox** [comment]
@dieterdemeyer can you give this a whirl with the latest release and make sure everything is kosher?

**Comment by rafaelfranca** [comment]
Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask. That said I'm closing this issue. Thank you.
