### ISSUE TITLE
Cairo module

### ISSUE THREAD

**Issue by mattheath** [boxen/our-boxen#373]
So this one was a pain, but it works and provides both `cairo` and `cairo::pycairo`

[mattheath/puppet-cairo](https://github.com/mattheath/puppet-cairo)

**Comment by seanknox** [comment]
@rafaelfranca @mattheath can this be merged in or closed?

**Comment by rafaelfranca** [comment]
Seems good to merge

**Comment by seanknox** [comment]
Hi @mattheath, I can't get your tests to run successfully. Can you update your spec `Puppetfile` with appropriate version updates? At the very least you'll need:

```puppet
mod 'boxen', '3.6.1', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.1.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
```
Sorry it's taken so long to respond to this.

**Comment by mattheath** [comment]
Ok, not sure when I'll get around to it, but will update when I can. Needless to say the versions in that file are from when I submitted the PR so likely rather out of date :wink:

**Comment by jacobbednarz** [comment]
Closing due to this issue being stale. If you can still reproduce or would like to continue this discussion, please let me know and I'll reopen this.
