### ISSUE TITLE
Duplicate declaration, File is already declared in file

### ISSUE THREAD

**Issue by Dagnan** [boxen/our-boxen#378]
Hi.

I' m trying to setup Boxen.

The full error is:

```
Error: Duplicate declaration: File[/Users/michel/.gemrc] is already declared in file /opt/boxen/repo/shared/boxen/manifests/gemrc.pp:10; cannot redeclare at /opt/boxen/repo/modules/people/manifests/dagnan.pp:65 on node macbook-air-de-michel-2.local
Error: Duplicate declaration: File[/Users/michel/.gemrc] is already declared in file /opt/boxen/repo/shared/boxen/manifests/gemrc.pp:10; cannot redeclare at /opt/boxen/repo/modules/people/manifests/dagnan.pp:65 on node macbook-air-de-michel-2.local
```

The file from where the problemes comes is https://github.com/Dagnan/fidzup-boxen/blob/master/modules/people/manifests/dagnan.pp

The gemrc is only declared once so I don't really understand what the problem is.

And after fixing it, what would be the correct way to relaunch boxes? Just script/boxen? Or nuking it before? Thanks!

**Comment by seanknox** [comment]
@Dagnan can this issue be closed?

**Comment by Dagnan** [comment]
I can't remember what I did or not, anyway you can close it. Thanks!

**Comment by seanknox** [comment]
I'm not a maintainer. Do you mind closing?
