### ISSUE TITLE
/opt/boxen/bin/boxen-git-credential erase: /opt/boxen/bin/boxen-git-credential: No such file or directory deploying Octopress

### ISSUE THREAD

**Issue by kyletcarlson** [boxen/our-boxen#384]
I removed Boxen a long time ago, and I got this error when I tried to deploy my Octopress blog to GitHub for the first time:

/opt/boxen/bin/boxen-git-credential erase: /opt/boxen/bin/boxen-git-credential: No such file or directory

Does anyone know where I might be able to find whatever settings file is trying to pull that boxen-git-credential file from?

**Comment by seanknox** [comment]
@kyletcarlson is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was originall reported. If it's still happening feel free to reopen.

**Comment by drom296** [comment]
this still happens

**Comment by seanknox** [comment]
@drom296 please open a new issue and make sure includes output from `boxen --debug`.

**Comment by drom296** [comment]
@seanknox no thanks. As the beginning of this thread says, this only happens after getting rid of boxen and thus came across this error. Therefore I cannot do what you ask.

I did find my solution though. In the .gitconfig, delete the credentials helper that points to boxen folders.
