### ISSUE TITLE
Boxen completely broken after fetching updates

### ISSUE THREAD

**Issue by AHaymond** [boxen/our-boxen#386]
I fetched and merged from `boxen/our-boxen` and now when I run the `boxen` command I get the following:

    Usage: boxen <service> <account> [<password>]

This message is not useful in the least. There is no documentation about what a service, or account is. Any help?

**Comment by seanknox** [comment]
@AHaymond is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
