### ISSUE TITLE
Adding stuff after boxen has run?

### ISSUE THREAD

**Issue by bitsandbooks** [boxen/our-boxen#393]
I've downloaded and run Boxen, which worked well. But now I need to install an additional software package (something I would normally install using Homebrew), but I can't figure out how to add something to my existing Boxen setup. How do I do this?

**Comment by seanknox** [comment]
@bitsandbooks Hi, can you close this issue? Thanks.

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
