### ISSUE TITLE
failed "script/boxen --no-fde" run

### ISSUE THREAD

**Issue by Alua-Kinzhebayeva** [boxen/our-boxen#398]
Hi!
When I run "script/boxen --no-fde" I get this:
➜  ~  cd /opt/boxen/repo
➜  repo git:(master) script/boxen --no-fde
/opt/boxen/repo/.bundle/ruby/1.8/gems/sawyer-0.3.0/lib/sawyer/resource.rb:93:in `method_missing': undefined method `email' for #<Sawyer::Resource:0x10da6ebf0> (NoMethodError)
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-2.0.0/lib/boxen/preflight/identity.rb:9:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-2.0.0/lib/boxen/check.rb:28:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-2.0.0/lib/boxen/check.rb:28:in `each'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-2.0.0/lib/boxen/check.rb:28:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-2.0.0/lib/boxen/cli.rb:44:in `run'
	from script/boxen:80
Could you suggest what went wrong?

**Comment by seanknox** [comment]
is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
