### ISSUE TITLE
Testing Boxen with Travis

### ISSUE THREAD

**Issue by petems** [boxen/our-boxen#401]
Travis CI now has OSX images for objective-c testing. So theoretically, you could do a basic smoke test of running the `script/boxen` after a change to make sure you didn't break anything. I'm going to see if it's possible this weekend.

If I can get a working version going I'll open a PR :+1:

**Comment by seanknox** [comment]
#364 and #713 is where activity to support this is happening— @petems mind closing this one?

**Comment by seanknox** [comment]
Closing this in favor of the work happening in the issues mentioned above.
