### ISSUE TITLE
“Device not configured” error when cloning Git repos over HTTP explained

### ISSUE THREAD

**Issue by drodriguez** [boxen/our-boxen#402]
I was trying to setup some projects under Boxen and I come across this problem also reported in several other tickets (like #286, #388, boxen/puppet-repository#7 and some others). I’m going to try to explain what I think it’s happening.

We have our repositories hosted using HTTP in several domains (imagine http://team1.company.local/ and http://common.company.local/). Boxen repository is on team1, projectX is on team1, but a submodule of projectX is in common.

When I tried to create a manifest for projectX I found out that while projectX checked out correctly, while trying to retrieve the submodules, the one in common was failing.

I noticed that the provisioning process wasn’t asking me for my username and password, as usual. I looked inside my Keychain and I found that there was only an entry for http://team1.company.local/, so I proceed to remove it and try to provision again.

This gave me the clue. Just after starting boxen I was asked for the username and password again for team1. Boxen was asking because it was trying to update Boxen itself, so when I got to cloning projectX repository, the credentials where already store in the Keychain.

So, why the submodule wasn’t asking for credentials as Boxen was doing? Well, that’s an interaction between Git and Puppet.

I started reading the [gitcredentials](https://www.kernel.org/pub/software/scm/git/docs/gitcredentials.html) help page and then the Git source code. It starts asking the credential helpers for username/password pairs for the domains, but if they fail, it tries to ask the user with a prompt. Those answers are used, and if successful, they are sent back to the credential helper to store them as valid credentials.

Then comes Puppet. Puppet execute method disconnects stdin (it sets it to /dev/null) and sends stdout to a temporal file. When Git prompt mechanism tries to read from /dev/null it receives an EOF, which is an error for the Git client, and it bails out with the strange error “Device not configured”.

At first I try Puppet to give a real stdin to the git process, adding `:stdin => '/dev/tty'`, but that didn’t seem to work. Then I tried using the `core.askpass` config value the Git help page was talking about.

A simple bash script proved not to work. Boxen wasn’t finishing, and it looked like I couldn’t even use stdin nor stdout from a child process of some command started by Puppet. Then I tried with a simple bash/AppleScript, popping a dialog to ask for user and password. And it worked… almost.

Trying to simplify my problem I created a manifest for projectX dependency, and I was testing with it. The new `core.askpass` worked like charm for that scenario, but it doesn’t seem to do the trick when trying to checkout the dependency as a projectX submodule. Seems like the credential helper is not queried either, because at this moment that Keychain entry is present, and the simple project uses it, while the submodule does not.

I will keep trying to understand what’s happening. I just leave this here  in case someone crosses the same problem, and has some better ideas. I will paste the `core.askpass` script below. You will also need to modify `site.pp` to add a `core.askpass` value just under `credential.helper` pointing to the script.

```
#! /bin/bash

# First arg is either "Username" or "Password"

function dialog {
  title=$1
  text=$2
  extra=$3

  dialog="display dialog \"${text}\" default answer \"\" with title \"${title}\" $extra"

  echo $dialog >> /tmp/askpass.log

  result=`/usr/bin/osascript <<EOT
on FrontmostApp()
  tell application "System Events" to get short name of first process whose frontmost is true
end FrontmostApp
tell application FrontmostApp()
  $dialog
  text returned of result
end tell
EOT`
  echo $result
}

case $1 in
Username*)
  dialog "Git" "$1" ""
  exit 0
  ;;
Password*)
  dialog "Git" "$1" "with icon caution with hidden answer"
  exit 0
  ;;
*)
  exit 1
  ;;
esac
```

**Comment by seanknox** [comment]
@drodriguez is this still an issue or can it be closed?

**Comment by drodriguez** [comment]
I stop using Boxen, so I don’t know if this is still an issue or other changes since then have fixed it or broken this situation even more. Sorry.

**Comment by seanknox** [comment]
Gotcha. Can you close this issue then? Thanks.
