### ISSUE TITLE
Error: change from directory to link failed: Could not remove existing file

### ISSUE THREAD

**Issue by marr** [boxen/our-boxen#407]
I am up to date with latest master () and running boxen gives me:

Boxen is up-to-date.
Notice: /Stage[main]//Node[default]/File[/Users/davidmarr/src/our-boxen]: Not removing directory; use 'force' to override
Notice: /Stage[main]//Node[default]/File[/Users/davidmarr/src/our-boxen]: Not removing directory; use 'force' to override
Error: Could not remove existing file
Error: /Stage[main]//Node[default]/File[/Users/davidmarr/src/our-boxen]/ensure: change from directory to link failed: Could not remove existing file

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
