### ISSUE TITLE
boxen::project not idempotent with Postgres databases

### ISSUE THREAD

**Issue by aharpole** [boxen/our-boxen#409]
If for some reason Boxen has an error when a user first runs it, they will fix the issue and run it again. When they run it again, they will inevitably get an error that the createdb command failed for their boxen::project manifest because the database already exists. 

Running createdb without first checking whether the database exists seems like it runs counter to the underlying philosophy of Puppet, which is that you describe the configuration you want, not give imperative commands. 

To work around this, I'm probably not going to have these projects do anything Postgres related, but instead I'll write a custom bootstrap script that handles database creation (and creation of database.yml) if needed, but it would be awesome if the project was indeed idempotent.

**Comment by seanknox** [comment]
@aharpole I know this isn't an issue currently, and vaguely recall this being an issue around the time you reported it. Closing.
