### ISSUE TITLE
Could not find suitable provider for augeas

### ISSUE THREAD

**Issue by dieterdemeyer** [boxen/our-boxen#414]
Hello,

I'm trying to use augeas resources in my setup, but I'm getting the error
```Could not find suitable provider for augeas```.

I guess there are some extra dependencies that are missing to make Puppet use the augeas provider.
Can someone indicate what extra packages need to installed ?
I would think ruby-agueas but I'm having issues getting this installed as a gem.
Augeas-devel is missing and I'm not sure on how to get this installed...

Thanks in advance.

**Comment by seanknox** [comment]
@dieterdemeyer is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
