### ISSUE TITLE
Dependency cycles when using run stages

### ISSUE THREAD

**Issue by dieterdemeyer** [boxen/our-boxen#419]
Hello,

I'm trying to use run stages but I seem to be getting dependency cycles on certain modules that are out of my control...
I have a preferences.pp with dock settings and I would like to run this in the ```runtime``` stage, after the ```main``` stage.
But then I get a dependency cycle, like the following:
![cycles](https://f.cloud.github.com/assets/523286/1307427/6ec87154-31bf-11e3-81e7-93805a9e42c1.png)

It's not just happening with the dockutil module, I've also seen this with the dnsmasq module as well...

Any insights into this would be appreciated.

Thanks.

**Comment by seanknox** [comment]
@dieterdemeyer can we close this?

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
