### ISSUE TITLE
Gem Command Not Found

### ISSUE THREAD

**Issue by deone** [boxen/our-boxen#452]
I finally, successfully install Boxen but when I run script/boxen, I get the message at this gist; https://gist.github.com/deone/7527595

In addition to this, I'm unable to run git commands from the repo directory, I get a message; hub: command not found. Same thing happens when I attempt running brew. I look into the boxen script and see that the script runs git commands just fine. Is there something I'm missing?

**Comment by seanknox** [comment]
@deone is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.

**Comment by deone** [comment]
I'm sorry for the delay in reply. I've been using boxen and can't even remember this error. So yes, it should be closed.
