### ISSUE TITLE
Puppet Hubflow

### ISSUE THREAD

**Issue by lazzurs** [boxen/our-boxen#458]
Hello,

I have created a module that will install hubflow for boxen users.

https://github.com/lazzurs/puppet-hubflow

Please let me know if you require any changes before forking under the boxen org.

**Comment by seanknox** [comment]
@tarebyte @rafaelfranca can this be merged in? 8+ months waiting.

**Comment by tarebyte** [comment]
@lazzurs does this need to be it's own module? Just from reading over the code that it looks like all it does is install the homebrew package I found here: https://github.com/Homebrew/homebrew/blob/698a68313635ae0e986b7f3c2dd2a8812c80f3b8/Library/Formula/hubflow.rb

**Comment by seanknox** [comment]
Agreed—if it's just a homebrew formula, just include it in a manifest. @lazzurs feel free to re-open if you have a good module use case.
