### ISSUE TITLE
Clear explanation missing on boxens puppet descriptions

### ISSUE THREAD

**Issue by thepian** [boxen/our-boxen#468]
It's great that there is a readme, but unless you use Boxen on a daily basis you have no clue how to apply most of it.

As an example

    # Set the global default ruby (auto-installs it if it can)
    class { 'ruby::global':
      version => '1.9.3'
    }

    # ensure a certain ruby version is used in a dir
    ruby::local { '/path/to/some/project':
      version => '1.9.3-p194'
    }

This is great, but where do I put these? Trial and error is the only answer I have come up with which is likely to be quicker than running through the boxen tutorials.

Boxen is very nicely done, and seems like a good structure, but it feels like vodoo.
I have no clue where to use what syntax and why, so all I know how to do is copy-paste to the right place. It seems to me that extensive examples and docs are key to success with boxen unless you are a master Ruby sys admin.

**Comment by seanknox** [comment]
@thepian is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.
