### ISSUE TITLE
puppet-rabbitmq

### ISSUE THREAD

**Issue by mschae** [boxen/our-boxen#470]
Good chance I did not see it. Is there really no rabbitmq module yet?

https://github.com/mschae/puppet-rabbitmq

As you can see I forked @crowdtap's repo (by @michaeldauria) who did all the heavy lifting. And I tried my best to copy the behavior of https://github.com/boxen/puppet-mysql and https://github.com/boxen/puppet-postgresql.

No tests yet as I am completely clueless how to write them for boxen.

Question: Is there any way to test a module without having to tag the repo every time I make a change? Pretty sure there has to be...

**Comment by seanknox** [comment]
@mschae please note that this is ready for review or close the issue—thanks!

**Comment by seanknox** [comment]
Closing this since it appears to have been abandoned. @mschae feel free to resubmit when ready for a review.
