### ISSUE TITLE
Installing from S3 - error

### ISSUE THREAD

**Issue by awsumco** [boxen/our-boxen#538]
First I am loving boxen great work, feel abit noobish asking this question but I feel I am missing something here. So Please excuse if this is the wrong place to ask, but I am out of ideas.

I am running the following puppet snipt:

        # Homebrew Package
                package { 'zsh':
                ensure => installed,
        }
However when it runs I get an error, I am copied the gdbm bit as thats the first dependency:

==> Installing zsh dependency: gdbm
Installing gdbm from S3...
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Error: /opt/boxen/homebrew/Cellar/gdbm/1.11 is not a directory
Warning: Bottle installation failed: building from source.
Warning: Nothing was installed to /opt/boxen/homebrew/Cellar/gdbm/1.11
Error: /opt/boxen/homebrew/Cellar/gdbm/1.11 is not a directory

Now from what I can tell the the tarball is not downloading from the S3 Bucket. So now my question is , am I missing som ENV vars somewhere. 

Oh this is a fresh install of Mavricks.

**Comment by seanknox** [comment]
@tarebyte can you close this? no update from the author.
