### ISSUE TITLE
No binaries inside the Boxen bottle of Bazaar

### ISSUE THREAD

**Issue by jamieconnolly** [boxen/our-boxen#599]
It seems that the Boxen bottle of Bazaar does not contain the necessary compiled binaries, but only the `man` pages. The `bin` and `libexec` folder are missing from the bottle.

When I try to depend on Bazaar in my custom Homebrew formula, it flags that Bazaar is installed (when in reality it only installs the `man` pages), and therefore causes the custom install to break because no `bzr` binary is found in `$PATH`.

The URL of the Boxen bottle is:
```
http://s3.amazonaws.com/boxen-downloads/homebrew/10.9/bazaar-2.6.0.tar.bz2
```

**Comment by seanknox** [comment]
@jamieconnolly is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing to due to lack of activity.
