### ISSUE TITLE
QUESTION: Agent orchestration for Boxen

### ISSUE THREAD

**Issue by addigy** [boxen/our-boxen#623]
First kudos on an amazing module... Boxen is AWESOME!

I believe most leverage boxen (since it's masterless) executing via a cron schedule.  However, I have a need to run more orchestrated updates via a persistent agent.  It looks like I may be able to leverage MCollective without a puppet master, but running this via a central web service may not be the most elegant.  There are other publish subscribe services that could help the Mac endpoint execute boxen, run a real-time facter audit, etc...  Do any of you have possible suggestions for an agent orchestration scheme for boxen/puppet-modules?

Many Thanks!
--Jason

**Comment by seanknox** [comment]
@addigy This is outside the scope of the project, methinks. AFAIK boxen is intended to be run by end users directly, or setup via a cronjob (which itself could be created via boxen). 

Please close this, thanks!
