### ISSUE TITLE
puppet-chromecast

### ISSUE THREAD

**Issue by nickpellant** [boxen/our-boxen#629]
[puppet-chromecast](http://github.com/nickpellant/puppet-chromecast) installs the [Chromecast](http://chromecast.com) application. Can this be added to the boxen organisation?

http://github.com/nickpellant/puppet-chromecast

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@seanknox it looks like chromecast is apart of homebrew cask. https://github.com/caskroom/homebrew-cask/blob/45a1bf6350d352172dd9876cfb36bae246652bb4/Casks/chromecast.rb

@nickpellant is this an acceptable substitute? I'm trying to avoid adding more module that are just application wrappers.

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.
