### ISSUE TITLE
where do i put code for custom facts?

### ISSUE THREAD

**Issue by nrser** [boxen/our-boxen#634]
i need to run a little ruby to find the location of something. i tried putting an `.rb` file in `/opt/boxen/repo/lib` and `/opt/boxen/repo/lib/facter`, but neither of these seemed to work.

**Comment by bval** [comment]
@nrser Did you ever find a good pattern for doing this?

**Comment by rafaelfranca** [comment]
I agree with @dgoodlad answer.

**Comment by nrser** [comment]
@bval i went with @dgoodlad answer: created `/opt/boxen/repo/modules/nrser/...` and added everything under there. thanks guys, sorry i never responded to the thread.

**Comment by bval** [comment]
Cool, thanks for closing the loop.
