### ISSUE TITLE
/etc/hiera.yaml is not found.

### ISSUE THREAD

**Issue by israelriibeiro** [boxen/our-boxen#649]
I tried to run ./hiera apache-service, i got nil when i created /etc/hiera.yaml
Am i doing something wrong? 

This is my config/hiera,yaml
```
:backends:
  - yaml
:yaml:
  :datadir: "%{::boxen_home}/repo/hiera"
:hierarchy:
  - "hosts/%{hostname}"
  - "users/%{github_login}"
  - common
:merge_behavior: deeper

```
This is my hiera/hosts/hostname.yaml
```
---
apache-service: apache2

```

I`d really if someone could help me. I`m newbie on boxen.

Thanks,

Israel Ribeiro

**Comment by seanknox** [comment]
@israelriibeiro is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.

**Comment by jhenahan** [comment]
Getting the same issue. `hiera` requires me to pass the Boxen config explicitly, then looks in the wrong place for, say, `common.yaml`.

`config/hiera.yaml`: As in `our-boxen`.

`hiera/common.yaml`:

    ---
    ruby::provider: 'chruby'
    hub::protocol: 'git'

Then:

    $ hiera hub::protocol
    Failed to start Hiera: RuntimeError: Config file /etc/hiera.yaml not found

With explicit config and `--debug`:

    $ hiera --debug --config config/hiera.yaml hub::protocol
    DEBUG: 2015-04-18 00:16:52 -0400: Hiera YAML backend starting
    DEBUG: 2015-04-18 00:16:52 -0400: Looking up hub::protocol in YAML backend
    DEBUG: 2015-04-18 00:16:52 -0400: Looking for data source common
    DEBUG: 2015-04-18 00:16:52 -0400: Cannot find datafile /repo/hiera/common.yaml, skipping
    nil
