### ISSUE TITLE
puppet-lightroom

### ISSUE THREAD

**Issue by tinygrasshopper** [boxen/our-boxen#650]
[puppet-lightroom](https://github.com/tinygrasshopper/puppet-lightroom) installs [Adobe Light Room](http://www.adobe.com/products/photoshop-lightroom.html)

https://github.com/tinygrasshopper/puppet-lightroom

**Comment by seanknox** [comment]
@dgoodlad @tarebyte can this be merged in? Been pending a response quite a while.

**Comment by tarebyte** [comment]
@seanknox @tinygrasshopper I would rather use homebrew cask if possible. I found lightroom here: https://github.com/caskroom/homebrew-cask/blob/cec67742ea6351453ba57a92653f08292f8a7d71/Casks/adobe-photoshop-lightroom.rb.

Is this an acceptable substitute?

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.
