### ISSUE TITLE
nuke --all --force does not remove github account name/password

### ISSUE THREAD

**Issue by njia** [boxen/our-boxen#654]
Hi there

I am testing our boxen installations and I just noticed `nuke --force --all` does not remove the saved github account/password info.

`nuke --force --all` removed `/opt/boxen` directory but after I cloned our repository, it won't ask for github account name.

Where did it save that info ?

Tried to put a question lable on this one but just could not find out how. anyone can show me how to do that ?

**Comment by seanknox** [comment]
@njia is this still an issue or can it be closed?
