### ISSUE TITLE
puppet-popcorntime

### ISSUE THREAD

**Issue by josanastrid** [boxen/our-boxen#657]
[puppet-popcorntime](https://github.com/josanastrid/puppet-popcorntime) installs [Popcorn-Time](https://popcorntime.io)

<https://github.com/josanastrid/puppet-popcorntime>

**Comment by radeksimko** [comment]
FYI: https://github.com/caskroom/homebrew-cask/pull/3954#issuecomment-44193511

> Popcorn Time was subject to DMCA takedowns when hosted on GitHub

**Comment by seanknox** [comment]
@tarebyte @josanastrid can this be merged in or the issue closed?

**Comment by tarebyte** [comment]
I think @radeksimko has a good point. If it was subject to a DCMA takedown I'd rather not add it in.

@johnbellone I apologize for taking so long with this issue.

**Comment by seanknox** [comment]
I think the DMCA concerns here are valid. I fear Boxen would simply receive a request to remove it as well. @josanastrid thanks for your work on this, sorry we can't merge it in!
