### ISSUE TITLE
Running boxen after upgrade throws Puppet::DataBinding::LookupError

### ISSUE THREAD

**Issue by stianselland** [boxen/our-boxen#661]
Hi there.

After upgrading to Boxen 2.6.0 I get the following error when running `boxen --debug`

```
Info: Loading facts in     /Users/stianselland/Documents/projects_real/boxen/repo/shared/stdlib/lib/facter/root_home.rb
Debug: importing '/Users/stianselland/Documents/projects_real/boxen/repo/shared/boxen/manifests/environment.pp' in environment production
Debug: Automatically imported boxen::environment from boxen/environment into production
Debug: hiera(): Hiera YAML backend starting
Debug: hiera(): Looking up boxen::environment::relative_bin_on_path in YAML backend
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /var/lib/hiera/common.yaml, skipping
Debug: hiera(): Hiera Module Data backend starting
Debug: hiera(): Looking up boxen::environment::relative_bin_on_path in Module Data backend
Error: uninitialized constant Puppet::DataBinding::LookupError at /Users/stianselland/Documents/projects_real/boxen/repo/manifests/site.pp:1 on node stians-macbook-pro.local
Wrapped exception:
uninitialized constant Puppet::DataBinding::LookupError
Error: uninitialized constant Puppet::DataBinding::LookupError at     /Users/stianselland/Documents/projects_real/boxen/repo/manifests/site.pp:1 on node stians-macbook-pro.local
```

I've followed the upgrade instructions [here](https://github.com/boxen/our-boxen/blob/master/docs/faq.md#q-how-do-you-upgrade-your-boxen-from-the-public-our-boxen).

From what I can see it looks like boxen is looking for a configuration key called `relative_bin_on_path`.

Cheers

Stian

**Comment by sachingupta771** [comment]
Hi, I’m facing same issue. Can u pls tell how did u started fresh boxen install since in my case it is remote gem thus looking for a way to do a fresh reinstallation.

**Comment by jacobbednarz** [comment]
Hi @sachingupta771,

Are you able to elaborate on what steps you've taken and any error messages you've received? This is a 3 year old issue so you're probably best creating a new issue with your specific environment details to help diagnose it.

**Comment by sachingupta771** [comment]
Hi  **@jacobbednarz**,
I'm getting the error while testing the unit test case file using rspec gem with puppet
Puppet::DataBinding::LookupError:
       Function lookup() did not find a value for the name 'profiles::ci::jenkins::user' at /app/hybris-devops/hybris/modules/profiles/spec/fixtures/modules/profiles/manifests/ci/jenkins/config.pp:1 on node
Thus was thinking of trying to reinstall boxen after reading above comments since I’m not able to trace the actual issue.

**Comment by jacobbednarz** [comment]
Based on that error message, it isn't anything to do with core Boxen - it's an issue with the Jenkins puppet module that is trying to find a value and you haven't provided a value for. I'd recommend taking a look at the module and following the setup ensuring you define the correct values in hiera.
