### ISSUE TITLE
puppet-mercurial

### ISSUE THREAD

**Issue by thejchap** [boxen/our-boxen#669]
https://github.com/thejchap/puppet-mercurial

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@thejchap it looks like this is a homebrew wrapper. Not entirely sure it needs it's own wrapper.

**Comment by seanknox** [comment]
Please re-open if installing view homebrew isn't sufficient.
