### ISSUE TITLE
puppet-optimal_layout

### ISSUE THREAD

**Issue by thejchap** [boxen/our-boxen#671]
https://github.com/thejchap/puppet-optimal_layout

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@seanknox these appears to be a homebrew cask for it: https://github.com/caskroom/homebrew-cask/blob/72d43fce59955032246c46519761ceb428820f5b/Casks/optimal-layout.rb

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.
