### ISSUE TITLE
puppet-fabric

### ISSUE THREAD

**Issue by marciok** [boxen/our-boxen#675]
https://github.com/marciok/puppet-fabric

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@mcauser @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/da28cb3e724c1a8cdf6949b954645b067e526bad/Casks/fabric.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@mcauser I apologize for getting to this so late.

**Comment by mcauser** [comment]
@marciok I believe he is referring to you

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.

**Comment by mcauser** [comment]
Sounds good
