### ISSUE TITLE
puppet-dragondisk

### ISSUE THREAD

**Issue by mcauser** [boxen/our-boxen#676]
https://github.com/mcauser/puppet-dragondisk

**Comment by seanknox** [comment]
@tarebyte @rafaelfranca can this be merged in or closed?

**Comment by tarebyte** [comment]
@mcauser @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/b352b306b7c151151c085b149ab9bf7d47021789/Casks/dragondisk.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@mcauser I apologize for getting to this so late.
