### ISSUE TITLE
puppet-fritzing

### ISSUE THREAD

**Issue by mcauser** [boxen/our-boxen#677]
https://github.com/mcauser/puppet-fritzing

**Comment by seanknox** [comment]
@tarebyte @rafaelfranca can this be merged in or closed?

**Comment by tarebyte** [comment]
@mcauser @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/13a89ee27d2c47923c8387b5e9ade5d3adfe6234/Casks/fritzing.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@mcauser I apologize for getting to this so late.
