### ISSUE TITLE
Error: Could not find dependency Class[Git]

### ISSUE THREAD

**Issue by xenolf** [boxen/our-boxen#678]
Hello!

I'm running boxen on a fresh Yosemite installation on my macbook pro to test a setup for my company but am unable to do so.
Every time I try to run the script it just spits the following error in my general direction and dies:

```
Error: Could not find dependency Class[Git] for Exec[clone /opt/boxen/repo] at /opt/boxen/repo/modules/boxen/manifests/repo.pp:18
```

The full output of the command is the following:

```
xen@wrk01:/opt/boxen/repo|master⇒  ./script/boxen
Boxen is up-to-date.
Notice: Compiled catalog for wrk01.local in environment production in 4.47 seconds
Error: Could not find dependency Class[Git] for Exec[clone /opt/boxen/repo] at /opt/boxen/repo/modules/boxen/manifests/repo.pp:18
```

Has anyone experienced this behaviour and could point me towards a fix?

Thanks!

**Comment by smcingvale** [comment]
@xenolf, how did you resolve this?  I'm running into the same issue.

    Error: Could not find dependency Class[Git] for Exec[clone /opt/boxen/repo] at /opt/boxen/repo/shared/boxen/manifests/repo.pp:18

**Comment by xenolf** [comment]
@smcingvale If I remember correctly it was because I did not use the correct version of the git package in my Puppetfile.

**Comment by smcingvale** [comment]
@xenolf, strangely, that didn't work for me.  But I got past it by requiring git in my site.pp manifest.  Thanks for your help.
