### ISSUE TITLE
puppet-eagle

### ISSUE THREAD

**Issue by mcauser** [boxen/our-boxen#681]
https://github.com/mcauser/puppet-eagle

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@mcauser @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/c1d43b6f58aec04de1416c26e9ffd06240b92c77/Casks/eagle.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@mcauser I apologize for getting to this so late.
