### ISSUE TITLE
puppet-balsamiq_mockups

### ISSUE THREAD

**Issue by mcauser** [boxen/our-boxen#682]
https://github.com/mcauser/puppet-balsamiq_mockups

**Comment by seanknox** [comment]
:+1: @tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@mcauser @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/0575fb31de8488bb7ebe0efbf2c2579eef6231c1/Casks/balsamiq-mockups.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@mcauser I apologize for getting to this so late.
