### ISSUE TITLE
Thoughts about officially supporting puppet-brewcask

### ISSUE THREAD

**Issue by tarebyte** [boxen/our-boxen#683]
Currently `boxen/our-boxen` has 28 open pull requests just for adding new modules to boxen. A lot of these are puppet wrappers for installing apps.

What does everyone think about trying to move towards officially supporting and maintaining our own fork of [puppet-brewcask](https://github.com/phinze/puppet-brewcask)?

I use it in my own boxen config, and it's a really clean solution of installing apps.

**Comment by petems** [comment]
Looks like this is done in https://github.com/boxen/boxen/issues/76 :smile:

**Comment by dgoodlad** [comment]
Yep, done!

**Comment by rafaelfranca** [comment]
Right. :smile:
