### ISSUE TITLE
Xcode CLTools Requirement

### ISSUE THREAD

**Issue by johnsoga** [boxen/our-boxen#684]
I'm new to boxen but looking over the suggested procedures for installation seem to leave installing the command line tools as optional if you've already installed Xcode. I installed boxen and then ssh'd in to my laptop start configuring and noticed this line appears after running `boxen --env`

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

Installed command line tools `xcode-select --install` and message went away not sure the relevance of the message but seems even if xcode is installed the command line tools are still required as well

Machine Information:
System Version: OS X 10.10.1 (14B25)
Kernel Version: Darwin 14.0.0

**Comment by seanknox** [comment]
@johnsoga On 10.9+, CLT is the minimum you need to install Boxen. Is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.
