### ISSUE TITLE
DiskMaker X module

### ISSUE THREAD

**Issue by hakamadare** [boxen/our-boxen#691]
https://github.com/hakamadare/puppet-diskmakerx

**Comment by seanknox** [comment]
:+1: @tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@hakamadare @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/b352b306b7c151151c085b149ab9bf7d47021789/Casks/diskmaker-x.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@hakamadare I apologize for getting to this so late.

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.
