### ISSUE TITLE
Unable to setup project with MySQL

### ISSUE THREAD

**Issue by toby-griffiths** [boxen/our-boxen#692]
Hi there,
I've just tried adding my first project, and it includes mysql => true, however when I run boxen I get the following error...
16:37 Notice: /Stage[main]/Projects::Client_website/Boxen::Project[Client Website]/Mysql::Db[client_test]/Exec[create mysql db client_test]/returns: You can check this by doing 'telnet 127.0.0.1 13306'
Error: mysqladmin -h127.0.0.1 -uroot -p13306 create client_test --password='' returned 1 instead of one of [0]
Error: /Stage[main]/Projects::Client_website/Boxen::Project[Client Website]/Mysql::Db[client_test]/Exec[create mysql db client_test]/returns: change from notrun to 0 failed: mysqladmin -h127.0.0.1 -uroot -p13306 create client_test --password='' returned 1 instead of one of [0]

I can't, for the life of me, work out how to ensure that the mysql service is up & running for the project.  I've tried various different ideas, none of which have worked.

Can someone help?

**Comment by jesseclark** [comment]
I found this [issue](https://github.com/boxen/puppet-mysql/issues/49) on the puppet-mysql issues tracker.

I resolved the issue per the last suggestion on that thread by changing: 
```mysql::socket: "%{mysql::datadir}/socket"``` 
in ```our_boxen/modules/mysql/data/Darwin.yaml``` to:
```mysql::socket: "%{::boxen::config::datadir}/mysql/socket"```

**Comment by jesseclark** [comment]
UPDATE

Looking at this [issue](https://github.com/boxen/our-boxen/issues/696) it seems that the modules directory shouldn't have copies of all the modules directories in it at all. 

I am discussing the solution further on the puppet-mysql [issue](https://github.com/boxen/puppet-mysql/issues/49) for anyone else who runs in to this issue.

**Comment by toby-griffiths** [comment]
Thanks for the comments,  Sorry for the delayed response.  Ended up using Vagrant to work around this till now.

So I've added the line...
```
mysql::socket: '%{::boxen::config::datadir}/mysql/socket'
```
... to my `heira/common.yaml` file, and all appears to be working great now.  Thanks

**Comment by toby-griffiths** [comment]
Thanks for your help @jesseclark .  I will get my head round boxen someday soon, thanks you the likes of you & the other helpful people on here :o)
