### ISSUE TITLE
modules directory 'filled' after update

### ISSUE THREAD

**Issue by tcooper** [boxen/our-boxen#696]
Finally got a chance to fetch/merge upstream changes from `boxen/our-boxen` into `our-boxen` to get it working on Yosemite again... :+1: 

Not sure if/what I did wrong in applying updates to `our-boxen` while following the [FAQ](https://github.com/boxen/our-boxen/blob/master/docs/faq.md#q-how-do-you-upgrade-your-boxen-from-the-public-our-boxen) but after the update a number of directories have *appeared* in my `our-boxen/modules` directory that were not there before...

```
    tcooper@velox:~/src/our-boxen $ boxen
    --> Preparing to auto-update...
    --> Skipping auto-update, because you've got uncommitted changes:

        ?? modules/adium/
    ?? modules/boxen/
    ?? modules/chrome/
    ?? modules/cord/
    ?? modules/dnsmasq/
    ?? modules/dockutil/
    ?? modules/foreman/
    ?? modules/gcc/
    ?? modules/git/
    ?? modules/go/
    ?? modules/homebrew/
    ?? modules/hub/
    ?? modules/inifile/
    ?? modules/iterm2/
    ?? modules/macvim/
    ?? modules/module_data/
    ?? modules/nginx/
    ?? modules/nodejs/
    ?? modules/openssl/
    ?? modules/osx/
    ?? modules/phantomjs/
    ?? modules/pkgconfig/
    ?? modules/repository/
    ?? modules/ruby/
    ?? modules/stdlib/
    ?? modules/sudo/
    ?? modules/textwrangler/
    ?? modules/vagrant/
    ?? modules/virtualbox/
    ?? modules/xquartz/

        Since you've got some uncommitted changes to those files, I'm
        going to take the safe road and not automatically update anything.
        If you're actively working on some Boxen, maybe you'd like to
        switch to a branch, rather than working on master? This way I'll
        know that you're trying something new, and won't do things like
        automatically update, or submit issues, while you're making
        changes. It makes everyone's life a bit easier :heart:

        Now, if you *weren't* expecting any changes, here's how to get
        back on the golden path:

          cd /opt/boxen/repo
          git reset --hard origin/master
          boxen

    For more info on how the simple git-based updates work, have a gander at
    https://github.com/boxen/our-boxen/blob/master/docs/updates.md

    Would you like to run Boxen anyway, without the latest updates? [y/N]
    N

    Ok, bailing out!
```
In addition, my customized `modules/people` and `modules/projects` trees were removed and had to be restored (with `git checkout -- <bit-that-was-gone>`)... :-1: 

Is this expected? If so, where can I read about this changed structure? If not, can I just remove all those **new** modules?

**Comment by jesseclark** [comment]
I also followed the FAQ and after running:
```
bundle install --no-deployment --without development --path .bundle
bundle exec librarian-puppet install --clean
```

I noticed that the modules directory had been filled AND the modules/people and modules/projects directories that were in there before had been removed. I was able to restore them from my remote repo but this seems like undesirable behavior.

**Comment by olofjohansson** [comment]
This is happening to me as well. I tried to rollback my local branch to the commit were I was when it was working, but it still happens.

Is this related to a specific version of Xcode and/or Command Line Tools?

I'm running
OS X 10.10.1
Xcode 6.1.1

**Comment by seanknox** [comment]
@tcooper is this still an issue or can it be closed?

**Comment by seanknox** [comment]
@tcooper @olofjohansson @jesseclark this is strange behavior. As pointed out above, the top-level `modules/` is for your personal or project manifests. Boxen modules are all in `shared/`. 

Are any of you modifying Boxen aside from `Puppetfile` or creating manifests? Trying to understand what's different about your Boxens.

**Comment by seanknox** [comment]
Actually, this issue was mentioned in https://github.com/boxen/our-boxen/issues/717, so I'm closing this one. Feel free to jump in there if this still an issue.
