### ISSUE TITLE
puppet-emacsosx

### ISSUE THREAD

**Issue by rhoml** [boxen/our-boxen#698]
https://github.com/rhoml/puppet-emacsosx

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@seanknox is this module available in Homebrew cask?

**Comment by seanknox** [comment]
@tarebyte indeed it is! @rhoml Please use `brew cask` to install emacs (you can have Boxen do so).
