### ISSUE TITLE
puppet-rescuetime

### ISSUE THREAD

**Issue by rhoml** [boxen/our-boxen#700]
https://github.com/rhoml/puppet-timerescue

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@rhoml @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/6a66da2e01e5d9b7b71921045aaeb810e22ff206/Casks/rescuetime.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@rhoml I apologize for getting to this so late.

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.

**Comment by rhoml** [comment]
So the idea is to remove default puppet providers? What happens if I don't want to use brew paths for everything?

**Comment by tarebyte** [comment]
@rhoml what is your use case that you don't want to use brew paths?

**Comment by rhoml** [comment]
It is just an idea, imagine that I want to install my packages on the applications folder instead of using brew for it. (Actually I dislike brew/ports)

**Comment by seanknox** [comment]
Check out brew cask. I think it does what you want.
