### ISSUE TITLE
Hitting Rate Limit while upgrading my boxen from public our-boxen

### ISSUE THREAD

**Issue by jesseclark** [boxen/our-boxen#705]
While following the [recommended steps](https://github.com/boxen/our-boxen/blob/master/docs/faq.md#q-how-do-you-upgrade-your-boxen-from-the-public-our-boxen) for upgrading my boxen from our-boxen I hit the API limit when executing: ```bundle exec librarian-puppet install --clean```.

I resolved the issue by setting the GITHUB_API_KEY environment variable to the API Key found in my Keychain. 

Is this the best way to resolve this issue and should we update the FAQ to inform people of the potential issue?

**Comment by seanknox** [comment]
@jesseclark Would be great to get this in the FAQ. You could submit a PR with essentially this comment: https://github.com/boxen/our-boxen/issues/443#issuecomment-29438819

**Comment by seanknox** [comment]
If you don't mind, please close this and open a PR. Thanks!
