### ISSUE TITLE
projects::all not including all projects

### ISSUE THREAD

**Issue by jesseclark** [boxen/our-boxen#707]
I created two project specific manifests in ```our_boxen/modules/projects/manifests/``` and in my personal manifest I have ```include projects::all``` yet when I run boxen my projects are not cloned into my src directory.

If I include the projects individually by name from my personal manifest they are cloned into the expected locations and configured correctly.

**Comment by seanknox** [comment]
@jesseclark project manifests should located in `modules/projects/manifests/`, e.g. `modules/projects/manifests/my_cool_project.pp`. In your project manifest, define its name:

```puppet
class projects::my_cool_project {
...
}
```

is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.
