### ISSUE TITLE
puppet-rstudio

### ISSUE THREAD

**Issue by taoistmath** [boxen/our-boxen#708]
https://github.com/taoistmath/puppet-rstudio

**Comment by seanknox** [comment]
@tarebyte can this be merged in or closed?

**Comment by tarebyte** [comment]
@taoistmath @seanknox there appears to be a homebrew cask formula for this: https://github.com/caskroom/homebrew-cask/blob/fd264c3e492defc1e69cac4bd8b2ffcb7bad474e/Casks/rstudio.rb.

I would rather not add anymore wrappers for applications unless that add something more to the functionality.

@taoistmath I apologize for getting to this so late.

**Comment by seanknox** [comment]
@tarebyte is correct: Boxen is using brewcask for OS X applications, so there is no need to wrap them in modules anymore. We are planning to deprecate the existing modules at boxen organization and improve the documentation about brewcask.
