### ISSUE TITLE
Support for github inclusion of the latest version

### ISSUE THREAD

**Issue by toby-griffiths** [boxen/our-boxen#709]
I was wondering if there is any way to include the latest version of a github puppet-xxx library without needing to update the tag number each time a new version of a package is released?

If not, is there any plan to add this feature?  I don't have much experience of Ruby or Puppet to offer a pull require for this, I'm afraid.

**Comment by dgoodlad** [comment]
@toby-griffiths have a look at the documentation for the [librarian-puppet project](https://github.com/rodjek/librarian-puppet), specifically the documentation for [Puppetfile](https://github.com/rodjek/librarian-puppet#puppetfile-breakdown). You should be able to use the `:ref` option to specify a non-tagged rev.
