### ISSUE TITLE
Where does the 'bin' set in PATH?

### ISSUE THREAD

**Issue by goofansu** [boxen/our-boxen#714]
```
$ echo $PATH
bin:/usr/local/bin:/usr/local/sbin:/opt/boxen/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```

I cannot find the place that set the 'bin' in PATH.

**Comment by bbck** [comment]
It's set by [puppet-boxen](https://github.com/boxen/puppet-boxen/blob/master/manifests/environment.pp#L8)

If you're looking to remove it, adding ```boxen::environment::relative_bin_on_path: false``` to hiera should work.

**Comment by rafaelfranca** [comment]
Right.

**Comment by goofansu** [comment]
@bbck Thanks :beer:
