### ISSUE TITLE
how to run boxen/boxen changes

### ISSUE THREAD

**Issue by addigy** [boxen/our-boxen#715]
I am experimenting with some boxen/boxen changes.  The our-boxen repo Gemfile pulls boxen/boxen from rubygems.org.  I changed my Gemfile to use a public git repo from my github account, to test some changes, but I receive a very weird issue near the end of the boxen install process:
```command
Error: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.3.0 already installed
Wrapped exception:
Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.3.0 already installed
Error: /Stage[main]/Git/Package[boxen/brews/git]/ensure: change from 2.3.0 to 2.1.4-boxen1 failed: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.3.0 already installed
```
I presume this is because the Gem is pulling the git dependency before boxen-homebrew attempts to run it's upgrade operation on git.  How do the rest of you customize and test boxen/boxen before checking-in changes to be published to rubygems?

Thanks in advance... this has unfortunately stumped me for quite a few hours now.

**Comment by tarebyte** [comment]
The error you posted usually happens if you have update a homebrew package that boxen manages outside of boxen.

As for boxen development in my personal config I opted in for all of the boxen repos and then point my personal boxen setup to use local copy with the branch in question.

**Comment by seanknox** [comment]
what @tarebyte said. @addigy is this still an issue or can it be closed?

**Comment by seanknox** [comment]
@addigy closing this—if it's still an issue feel free to re-open with more details.
