### ISSUE TITLE
Document local webserver changes

### ISSUE THREAD

**Issue by rossmcf** [boxen/our-boxen#723]
Hi,

Previously, my mac used apache out of the box, with local sites hosted in either `~/Sites` or `/Library/Webserver/Documents`. With boxen, I appear to have an nginx server running. It would be good to have some docs on where the docroot for this install lives, and how it's configured.

Thanks,
Ross

**Comment by gblair** [comment]
Maybe [the project module README](https://github.com/boxen/our-boxen/blob/master/modules/projects/README.md) can help you. Your project would typically be sourced from a github repo, and configured with a project manifest (at `/opt/boxen/modules/projects/manifests/myproject.pp`, for example), as described in the README. Then you could go into your terminal and do the following to get the whole thing set up:
```
boxen myproject
```
The default `boxen::project` module (used in the example in the README) is for rails projects. If you are using a different environment (e.g. some kind of PHP-based stack), you will want to use a different class in your project module, like [the one provided by puppet-php](https://github.com/boxen/puppet-php#php-project-usage), for example.  You would make other modules, like `puppet-php`, available to boxen (Puppet) by adding them to the Puppetfile in your boxen.  

Once boxen has run, you will end up with a folder at `~/src/myproject` from whence nginx will serve your site on the URL `http://myproject.dev`. By default, `boxen::project` will create mysql databases called `myproject_development` and `myproject_test`, I believe. Other modules may handle database setup differently.  You can access the database using the `root` user with no password (also by default).

Good luck!

**Comment by seanknox** [comment]
@rossmcf mind closing this?
