### ISSUE TITLE
puppet-radiant_player

### ISSUE THREAD

**Issue by spacepants** [boxen/our-boxen#730]
Hi, I made a module for [Radiant Player](https://github.com/kbhomes/radiant-player-mac) to make it faster to pump some sweet jams.
https://github.com/spacepants/puppet-radiant_player

**Comment by rafaelfranca** [comment]
Boxen is using Brewcask to install OSX applications now. So there is no need to create modules anymore. See https://github.com/boxen/our-boxen/tree/master/hiera/users#example

**Comment by spacepants** [comment]
Oh sweet, this is way better! Thanks for letting me know.
