### ISSUE TITLE
new module puppet-ohmyzsh

### ISSUE THREAD

**Issue by fernandes** [boxen/our-boxen#733]
In https://github.com/boxen/our-boxen/issues/505 @erivello proposed a new puppet-ohmyzsh module, as he stopped replying on the issue.

I'm opening this one with my fork keeping original work.

This is my first submit, if anything wrong, or if needs to be improved I'm ready to do it

//cc @seanknox

**Comment by seanknox** [comment]
Hi @fernandes, please provider a link to your module repo and once it gets an ok, we'll fork it to the `boxen` organization and make you an owner.

**Comment by fernandes** [comment]
ohhhh my bad!!! really really sorry hehehhe

here its: https://github.com/fernandes/puppet-ohmyzsh

thank you

**Comment by fernandes** [comment]
hi @seanknox , is the module ok?

thank you

**Comment by seanknox** [comment]
Hi @fernandes, this a lot of support code that ultimately just executes one-line shell command. If there was more complexity that warranted a specialized module I could get on board, but this should be handled in a personal/project manifest.

**Comment by fernandes** [comment]
hi @seanknox ... thank you for you comment, submitted because of #505, but no problem... I'm gonna improve it then I reopen this issue when ready

thank you for your attention
