### ISSUE TITLE
Bump gcc and ruby module versions

### ISSUE THREAD

**Issue by seanknox** [boxen/our-boxen#744]
- Latest puppet-gcc release works on systems with latest XCode/CLT— their clang broke gcc compilation.
- Latest puppet-ruby has a number of fixes and enhancements.

**Comment by pfista** [comment]
+1

**Comment by jacobbednarz** [comment]
Closing due to this issue being stale. If you can still reproduce or would like to continue this discussion, please let me know and I'll reopen this.
