### ISSUE TITLE
Could not retrieve facts for <machine>.local: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by wchrisjohnson** [boxen/our-boxen#758]
I am seeing the following attempting to an initial boxen on my machine:

:repo $ ./script/boxen --no-fde --debug
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
/opt/boxen/repo/bin/librarian-puppet install --path=/opt/boxen/repo/shared --verbose
[Librarian] Ruby Version: 2.0.0
[Librarian] Ruby Platform: universal.x86_64-darwin14
[Librarian] Rubygems Version: 2.0.14
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 1.0.9
[Librarian] Project: /opt/boxen/repo
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/bin/git
[Librarian] Git Version: 2.3.2
[Librarian] Git Environment Variables:
[Librarian] GITHUB_API_TOKEN=[token]
[Librarian] Pre-Cached Sources:
[Librarian] [:github_tarball, "boxen/puppet-boxen", {}]
[Librarian] [:github_tarball, "boxen/puppet-brewcask", {}]
[Librarian] [:github_tarball, "boxen/puppet-dnsmasq", {}]
[Librarian] [:github_tarball, "boxen/puppet-foreman", {}]
[Librarian] [:github_tarball, "boxen/puppet-gcc", {}]
[Librarian] [:github_tarball, "boxen/puppet-git", {}]
[Librarian] [:github_tarball, "boxen/puppet-go", {}]
[Librarian] [:github_tarball, "boxen/puppet-homebrew", {}]
[Librarian] [:github_tarball, "boxen/puppet-hub", {}]
[Librarian] [:github_tarball, "puppetlabs/puppetlabs-inifile", {}]
[Librarian] [:github_tarball, "ripienaar/puppet-module-data", {}]
[Librarian] [:github_tarball, "boxen/puppet-nginx", {}]
[Librarian] [:github_tarball, "boxen/puppet-nodejs", {}]
[Librarian] [:github_tarball, "boxen/puppet-openssl", {}]
[Librarian] [:github_tarball, "boxen/puppet-phantomjs", {}]
[Librarian] [:github_tarball, "boxen/puppet-pkgconfig", {}]
[Librarian] [:github_tarball, "boxen/puppet-repository", {}]
[Librarian] [:github_tarball, "boxen/puppet-ruby", {}]
[Librarian] [:github_tarball, "puppetlabs/puppetlabs-stdlib", {}]
[Librarian] [:github_tarball, "boxen/puppet-sudo", {}]
[Librarian] [:github_tarball, "boxen/puppet-xquartz", {}]
[Librarian] Post-Cached Sources:
[Librarian] [:github_tarball, "boxen/puppet-boxen", {}]
[Librarian] [:github_tarball, "boxen/puppet-brewcask", {}]
[Librarian] [:github_tarball, "boxen/puppet-dnsmasq", {}]
[Librarian] [:github_tarball, "boxen/puppet-foreman", {}]
[Librarian] [:github_tarball, "boxen/puppet-gcc", {}]
[Librarian] [:github_tarball, "boxen/puppet-git", {}]
[Librarian] [:github_tarball, "boxen/puppet-go", {}]
[Librarian] [:github_tarball, "boxen/puppet-homebrew", {}]
[Librarian] [:github_tarball, "boxen/puppet-hub", {}]
[Librarian] [:github_tarball, "puppetlabs/puppetlabs-inifile", {}]
[Librarian] [:github_tarball, "ripienaar/puppet-module-data", {}]
[Librarian] [:github_tarball, "boxen/puppet-nginx", {}]
[Librarian] [:github_tarball, "boxen/puppet-nodejs", {}]
[Librarian] [:github_tarball, "boxen/puppet-openssl", {}]
[Librarian] [:github_tarball, "boxen/puppet-phantomjs", {}]
[Librarian] [:github_tarball, "boxen/puppet-pkgconfig", {}]
[Librarian] [:github_tarball, "boxen/puppet-repository", {}]
[Librarian] [:github_tarball, "boxen/puppet-ruby", {}]
[Librarian] [:github_tarball, "puppetlabs/puppetlabs-stdlib", {}]
[Librarian] [:github_tarball, "boxen/puppet-sudo", {}]
[Librarian] [:github_tarball, "boxen/puppet-xquartz", {}]
[Librarian] The specfile is unchanged: nothing to do.
[Librarian] Install: dependencies resolved
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian] [:github_tarball, "boxen/puppet-boxen", {}]
[Librarian] [:github_tarball, "ripienaar/puppet-module-data", {}]
[Librarian] [:github_tarball, "boxen/puppet-brewcask", {}]
[Librarian] [:github_tarball, "boxen/puppet-dnsmasq", {}]
[Librarian] [:github_tarball, "boxen/puppet-foreman", {}]
[Librarian] [:github_tarball, "boxen/puppet-gcc", {}]
[Librarian] [:github_tarball, "boxen/puppet-git", {}]
[Librarian] [:github_tarball, "boxen/puppet-go", {}]
[Librarian] [:github_tarball, "boxen/puppet-homebrew", {}]
[Librarian] [:github_tarball, "boxen/puppet-hub", {}]
[Librarian] [:github_tarball, "puppetlabs/puppetlabs-inifile", {}]
[Librarian] [:github_tarball, "boxen/puppet-nginx", {}]
[Librarian] [:github_tarball, "boxen/puppet-nodejs", {}]
[Librarian] [:github_tarball, "boxen/puppet-openssl", {}]
[Librarian] [:github_tarball, "boxen/puppet-phantomjs", {}]
[Librarian] [:github_tarball, "boxen/puppet-pkgconfig", {}]
[Librarian] [:github_tarball, "boxen/puppet-repository", {}]
[Librarian] [:github_tarball, "boxen/puppet-ruby", {}]
[Librarian] [:github_tarball, "puppetlabs/puppetlabs-stdlib", {}]
[Librarian] [:github_tarball, "boxen/puppet-sudo", {}]
[Librarian] [:github_tarball, "boxen/puppet-xquartz", {}]
[Librarian] Installing boxen/3.10.4 
[Librarian] Installing brewcask/0.0.6 
[Librarian] Installing dnsmasq/2.0.1 
[Librarian] Installing foreman/1.2.0 
[Librarian] Installing gcc/2.2.1 
[Librarian] Installing git/2.7.9 
[Librarian] Installing go/2.1.0 
[Librarian] Installing homebrew/1.12.0 
[Librarian] Installing hub/1.4.1 
[Librarian] Installing inifile/1.1.1 
[Librarian] Installing module_data/0.0.3 
[Librarian] Installing nginx/1.4.5 
[Librarian] Installing nodejs/4.0.1 
[Librarian] Installing openssl/1.0.0 
[Librarian] Installing phantomjs/2.4.0 
[Librarian] Installing pkgconfig/1.0.0 
[Librarian] Installing repository/2.4.1 
[Librarian] Installing ruby/8.5.2 
[Librarian] Installing stdlib/4.2.1 
[Librarian] Installing sudo/1.0.0 
[Librarian] Installing xquartz/1.2.1 
/opt/boxen/repo/bin/puppet apply --group admin --confdir /tmp/boxen/puppet/conf --vardir /tmp/boxen/puppet/var --libdir /opt/boxen/repo/lib --libdir /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.2/lib --modulepath /opt/boxen/repo/modules:/opt/boxen/repo/shared --hiera_config /opt/boxen/repo/config/hiera.yaml --logdest /opt/boxen/repo/log/boxen.log --logdest console --no-report --detailed-exitcodes --show_diff --debug /opt/boxen/repo/manifests
Debug: Runtime environment: puppet_version=3.7.1, ruby_version=2.0.0, run_mode=user, default_encoding=UTF-8
Debug: Loading external facts from /opt/boxen/repo/shared/boxen/facts.d
Info: Loading facts
Debug: Loading facts from /opt/boxen/repo/shared/boxen/lib/facter/boxen.rb
Debug: Loading facts from /opt/boxen/repo/shared/boxen/lib/facter/boxen_facts_d.rb
Debug: Loading facts from /opt/boxen/repo/shared/boxen/lib/facter/root_encrypted.rb
Info: Loading facts
Debug: Loading facts from /opt/boxen/repo/shared/brewcask/lib/facter/brewcask_root.rb
Info: Loading facts
Debug: Loading facts from /opt/boxen/repo/shared/foreman/lib/facter/foreman_version.rb
Info: Loading facts
Debug: Loading facts from /opt/boxen/repo/shared/homebrew/lib/facter/homebrew_bottle_url.rb
Debug: Loading facts from /opt/boxen/repo/shared/homebrew/lib/facter/homebrew_root.rb
Info: Loading facts
Debug: Loading facts from /opt/boxen/repo/shared/stdlib/lib/facter/facter_dot_d.rb
Debug: Loading facts from /opt/boxen/repo/shared/stdlib/lib/facter/pe_version.rb
Debug: Loading facts from /opt/boxen/repo/shared/stdlib/lib/facter/puppet_vardir.rb
Debug: Loading facts from /opt/boxen/repo/shared/stdlib/lib/facter/root_home.rb
Error: Could not run: Could not retrieve facts for .local: A JSON text must at least contain two octets!

I have commented out the node and ruby items in site.pp. I have removed all my customizations except those lines I commented out.

**Comment by jacobbednarz** [comment]
Hi @wchrisjohnson! Thanks for opening an issue, unfortunately it's been a while and it hasn't been updated. Could you please let me know if this is still an issue? I'm going to close this off but if you reply I'll gladly open it back up and help you work through the problem.
