### ISSUE TITLE
Add puppet-paw for Boxen

### ISSUE THREAD

**Issue by jacobbednarz** [boxen/our-boxen#761]
I've added a module for installing [Paw](https://luckymarmot.com/paw) via Boxen. The source repository is: https://github.com/jacobbednarz/puppet-paw

Could you please review it and let me know if it's fine to fork? 

Thanks!

**Comment by timdorr** [comment]
If it's just a simple app, it's better to just use brew cask, since there is less overhead. It's already available: https://github.com/caskroom/homebrew-cask/blob/master/Casks/paw.rb

Then you can just do this:
```puppet
package { 'paw':
  provider => 'brewcask'
}
```

**Comment by jacobbednarz** [comment]
Thanks, closing this one off in favour of brewcask.
