### ISSUE TITLE
gpg cannot open `/dev/tty'

### ISSUE THREAD

**Issue by josephDunne** [boxen/our-boxen#763]
Hi, I am trying a setup that requires a git repo encrypted using [blackbox](https://github.com/StackExchange/blackbox) which makes use of gpg/gpg-agent

So after setting things up I have the following Exec resource:
```ruby
$blackbox_dir = '/usr/local/share/blackbox'
$blackbox_bin = "${blackbox_dir}/bin"
$blackbox_decrypt = "${blackbox_bin}/blackbox_edit_start"
$blackbox_dotfiledir = "som_dir/dotfiles"
$blackbox_dotfile = 'dotfiles/*'

exec { 'unencrypt dotfiles':
    provider    => shell,
    command  => "${blackbox_decrypt} ${blackbox_dotfile}",
    cwd           => $people::josephDunne::config::blackbox_dir,
    creates      => "${blackbox_dotfiledir}/env.zsh",
    require      =>  Repository['/usr/local/share/blackbox'],
  }
```

but this generates:
```
Notice: /Stage[main]/People::Josephdunne::Blackbox/Exec[unencrypt dotfiles]/returns: gpg: cannot open `/dev/tty': Device not configured
Error: /usr/local/share/blackbox/bin/blackbox_edit_start dotfiles/* returned 2 instead of one of [0]
Error: /Stage[main]/People::Josephdunne::Blackbox/Exec[unencrypt dotfiles]/returns: change from notrun to 0 failed: /usr/local/share/blackbox/bin/blackbox_edit_start dotfiles/* returned 2 instead of one of [0]
```

Is this a sudo issue? How does boxen handle these kinds of commands?

**Comment by josephDunne** [comment]
I get this with a lot of packages. here is another one:

```ruby
package { 'rust':
     ensure   => present,
     provider => 'brewcask'
 }
```

**Comment by jacobbednarz** [comment]
Hi @josephDunne! Thanks for opening an issue, unfortunately it's been a while and it hasn't been updated. Could you please let me know if this is still an issue? I haven't used blackbox myself but I'm happy to help you debug this one if you're still seeing it. I'm going to close this off but if you reply I'll gladly open it back up and help you work through the problem.
