### ISSUE TITLE
Update puppet-librarian

### ISSUE THREAD

**Issue by jaxxstorm** [boxen/our-boxen#784]
I'm trying to use boxen with an updated version of puppet-librarian, because the bundled versions 1.0.9 lacks a load of features like referencing by git commit and such like.

However, I'm struggling. I updated the gemfile and it seems boxen depends explicitly on 1.0.9.

Is there an instruction set for this? I'll happily submit a PR if I can get this working

**Comment by webflo** [comment]
+1 the bundled version feels sluggish

**Comment by timdorr** [comment]
You can do it like this:

1. Fork [boxen/boxen](https://github.com/boxen/boxen)
2. In your own `our-boxen`, point the [`Gemfile`](https://github.com/boxen/our-boxen/blob/master/Gemfile) to your fork.
3. Do whatever updates you'd like to try in your `boxen` fork. 
4. `bundle update boxen` in your our-boxen.
5. See if anything busted.

And when you're done and satisfied nothing is on fire, submit some PRs! :smile:
