### ISSUE TITLE
unable to install on clean El Captain, error is: Puppetfile:41: syntax error, unexpected <<, expecting end-of-input (SyntaxError)

### ISSUE THREAD

**Issue by wcorrigan** [boxen/our-boxen#793]
I have a new system, 10.11.1, with Xcode up to date. 
I'm trying to get boxen setup on it. Boxen works great on my other machine, Yosimite, installed 9 mos. ago. 
Seems to be a problem with one of the ruby files. Should I edit this file? 
When I run ./script/boxen, 
This is what I get:
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl/receiver.rb:30:in `instance_eval': /opt/boxen/repo/Puppetfile:41: syntax error, unexpected <<, expecting end-of-input (SyntaxError)
<<<<<<< HEAD
  ^
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl/receiver.rb:30:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/dsl.rb:47:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/dsl.rb:34:in `block in run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/dsl.rb:28:in `tap'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/dsl.rb:28:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/dsl.rb:17:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/environment.rb:148:in `dsl'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/specfile.rb:15:in `read'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:17:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/cli.rb:67:in `install'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/bin/librarian-puppet:7:in `<top (required)>'
	from /opt/boxen/repo/bin/librarian-puppet:16:in `load'
	from /opt/boxen/repo/bin/librarian-puppet:16:in `<main>'
Can't run Puppet, fetching dependencies with librarian failed.

**Comment by takashiyoshida** [comment]
You should check your Puppetfile (line 41?). Maybe you were merging some changes and did not resolve conflicts completely?

**Comment by wcorrigan** [comment]
Thank you. I don't know what the <<<<<<< HEAD means, but I retrieved Puppetfile from our-boxen repo and got past this error.
