### ISSUE TITLE
Created puppet-varnish module

### ISSUE THREAD

**Issue by qrz-io** [boxen/our-boxen#803]
https://github.com/qrz-io/puppet-varnish

It installs varnish and adds a service to Boxen. There is however a bug I can't really figure out: https://github.com/qrz-io/puppet-varnish/issues/1 any help would be appreciated.

**Comment by jacobbednarz** [comment]
Thanks for your contribution! I'm not really on the fence about whether it's worth including this module as `varnish` can already installed [using homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/varnish.rb) and from the looks of it you are already leveraging this inside of your module so I'm not sure if it is just as easy to point people at using the homebrew version. Thoughts?

**Comment by qrz-io** [comment]
Apologies, it appears I've missed this comment!

Well, I sort of agree, pointing would be certainly easier. I was kind of thinking of having Boxen install projects with everything they need - including the php and nginx configs, a database and varnish configs if needed. For instance, configure boxen to make nginx listen to port 8081 and varnish listen to port 80 with its backend on port 8081.

The possibility to modify the nginx port was added in https://github.com/boxen/puppet-nginx/pull/47

**Comment by jacobbednarz** [comment]
Sounds good. I've forked the repository into the Boxen organisation and added you to the @boxen/puppet-varnish-maintainers group. Have fun!
