### ISSUE TITLE
Already evaluated at rest

### ISSUE THREAD

**Issue by habitullence** [boxen/our-boxen#806]
I'm getting the following output:

```
Already evaluated rest at /opt/boxen/repo/.bundle/ruby/2.0.0/gems/facter-2.4.4-universal-darwin/lib/facter/ec2.rb:21, reevaluating anyways
Already evaluated rest at /opt/boxen/repo/.bundle/ruby/2.0.0/gems/facter-2.4.4-universal-darwin/lib/facter/ec2.rb:38, reevaluating anyways
Already evaluated rest at /opt/boxen/repo/.bundle/ruby/2.0.0/gems/facter-2.4.4-universal-darwin/lib/facter/gce.rb:4, reevaluating anyways
```

I believe it's caused by multiple binaries, as per https://tickets.puppetlabs.com/browse/FACT-634, but I can't figure out how to fix it.

**Comment by habitullence** [comment]
I've completely removed and re-installed Boxen, still getting the same errors.

**Comment by habitullence** [comment]
The only thing I can see is inside /opt/boxen/repo/.bundle/ruby/2.0.0/gems/facter-2.4.4-universal-darwin/lib/facter/* define_resolution(:rest) is mentioned 3 times, maybe this has something to do with it.

**Comment by habitullence** [comment]
This is indeed caused by multiple facter installs. I had facter, hiera, and puppet installed from the [package installers](http://downloads.puppetlabs.com/mac/?_ga=1.72772309.714034401.1451908122). To fix, downloaded them, run the installer, and remove all the files listed in File > Show Files (Cmd-I).

**Comment by jacebrowning** [comment]
I simply deleted `/opt/boxen/repo/.bundle/ruby/2.0.0/gems/facter-*` to resolve the issue on my machine.
