### ISSUE TITLE
rbenv & bundler  - not loading bundler/setup 

### ISSUE THREAD

**Issue by brettswift** [boxen/our-boxen#807]
The rbenv setup here seems to become a pain when working with rspec on dev projects.  It seems like bundler isn't working.   A lot of boxen users are ruby devs so I'm thinking this is something that might not be a bug with our-boxen.   If it isn't then maybe someone can point me in a direction to get out of this ruby environment hell that I'm in. 

```
Error was /opt/boxen/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError) (RuntimeError)
```

What other information can I supply to help figure out what is going on here?

I've seen this error all over the place on the googles, but nothing has seemed to help. 

```
$ : bundler --version                                                                                   
Bundler version 1.11.2

$ : ruby --version                                                                                        
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]

$ which ruby                                                                                            
/opt/boxen/rbenv/shims/ruby
```

**Comment by jacobbednarz** [comment]
@brettswift I've been unable to replicate this - Do you have a sample public repository I can try this on?

**Comment by jacobbednarz** [comment]
Closing due to this issue being stale. If you can still reproduce or would like to continue this discussion, please let me know and I'll reopen this.

**Comment by brettswift** [comment]
Hey, sorry for not replying to this thread. 

I've stopped using boxen.  It's just been kind of flakey for me.  Might be better if there were 10 others using the boxen project but with just me it's not worth the maintenance effort.
