### ISSUE TITLE
Problem with Node install - "Version must be like vN.N.N" - again

### ISSUE THREAD

**Issue by henscu** [boxen/our-boxen#808]
I just updated to the latest version of Boxen, and when I run it I get the following error:

`Error: Parameter version failed on Nodejs[0.8]: Version must be like vN.N.N, not 0.8 at /opt/boxen/repo/modules/nodejs/manifests/version.pp:52
Wrapped exception:
Version must be like vN.N.N, not 0.8`

When I changed **manifests/site.pp** to have a node.js version of 0.8.0, I still get the error:

`Error: Parameter version failed on Nodejs[0.8.0]: Version must be like vN.N.N, not 0.8.0 at /opt/boxen/repo/modules/nodejs/manifests/version.pp:52
Wrapped exception:
Version must be like vN.N.N, not 0.8.0`

I have seen related issues like #689 but that issue refers to underscores being used in node.js versions in site.pp, and it has been fixed.

Any idea what is causing this error?

**Comment by henscu** [comment]
Mea culpa, so closing this.

I hadn't updated Boxen in ages and when I did, my site.pp was not updated, so the formats for node.js versions were still N.N.N and consequently produced the above error when I ran Boxen.

So, my fix was simply to manually update the versions to vN.N.N...

**Comment by jacobbednarz** [comment]
Thanks @henscu! Glad it was resolved. :smile:
