### ISSUE TITLE
`brew update` failes after upgrading to homebrew 0.9.9

### ISSUE THREAD

**Issue by hakamadare** [boxen/our-boxen#814]
After upgrading homebrew to the latest version (apparently over the past weekend the maintainers split it into Homebrew/brew and Homebrew/homebrew-core?), I now get the following Puppet error when running `boxen`:

```
Debug: Executing 'brew update'
Error: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Error: /Stage[main]/Homebrew::Repo/Homebrew_repo[/opt/boxen/homebrew]/min_revision: change from 342ed4c830e349efee4cf4719d44eae96112cd47 to e90b6e9ded2fd2c73a4e0d93f5dbc5b075a61b7c failed: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

Looks like something has changed upstream?  attn @jacobbednarz who seems to be working on something related

**Comment by wfarr** [comment]
Yeah. Appears homebrew has split up formulae from the package manager itself (a change I am quite happy to see!) but we'll want to fix a few things on boxen's side for compatibility with the new world order.

**Comment by jacobbednarz** [comment]
Yep! I'm tackling a asort term fix at https://github.com/boxen/puppet-homebrew/pull/92 and once we get everyone working again, I'll take a look at getting it working using the split repository setup.

**Comment by mikemcquaid** [comment]
Made a release in https://github.com/boxen/puppet-homebrew/releases/tag/2.0.1.

**Comment by hakamadare** [comment]
@mikemcquaid thanks for that!  i just modified my Puppetfile to pull puppet-homebrew 2.0.1 (and have confirmed that there's a 2.0.1 module downloaded by librarian-puppet), but i still see the same error message; is there something else i need to do to implement the short term fix?

**Comment by jacobbednarz** [comment]
I'll be updating our-boxen shortly with 2.0.1 if you'd like to test that out?

**Comment by mikemcquaid** [comment]
@hakamadare I haven't personally investigated this. It may need a more involved fix. I'm not personally using Boxen any more but if people are still struggling in a few days I can try and boot up a VM and check it out.

**Comment by jacobbednarz** [comment]
@hakamadare check out #815 as the proposed fix. You should be able to checkout this branch locally and run `boxen` with a working homebrew again.

**Comment by mikemcquaid** [comment]
Made another release in https://github.com/boxen/puppet-homebrew/releases/tag/2.0.2.

**Comment by snewman** [comment]
This fixes it for me. Going to send a pull request over to our-boxed as it's currently pegged to the old (now breaking) 2.0.1

**Comment by jacobbednarz** [comment]
@snewman I've got one open via #816 however I before merging I was interested in the reasoning behind why using root has all of a sudden broke.

**Comment by snewman** [comment]
Ah, gotcha!

**Comment by hakamadare** [comment]
https://github.com/boxen/puppet-homebrew/releases/tag/2.0.2 works for me, thanks!

**Comment by vesan** [comment]
It seems I'm unable to get this to work.

The error I'm getting when running `script/boxen` is:

Error: Execution of 'brew update' returned 1: Error: Running Homebrew as root is extremely dangerous. As Homebrew does not
drop privileges on installation you are giving all build scripts full access
to your system. As a result of the macOS sandbox not handling the root user
correctly HOMEBREW_NO_SANDBOX has been set so the sandbox will not be used. If
we have not merged a pull request to add privilege dropping by November 1st
2016 running Homebrew as root will be disabled. No Homebrew maintainers plan
to work on this functionality.
Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Error: /Stage[main]/Homebrew::Repo/Homebrew_repo[/opt/boxen/homebrew]/min_revision: change from 7ac90613fd5a9719a03e180947522bfd4a8790be to e07584e3fbdc88327bafe23b9c40c904d0fff0a1 failed: Execution of 'brew update' returned 1: Error: Running Homebrew as root is extremely dangerous. As Homebrew does not
drop privileges on installation you are giving all build scripts full access
to your system. As a result of the macOS sandbox not handling the root user
correctly HOMEBREW_NO_SANDBOX has been set so the sandbox will not be used. If
we have not merged a pull request to add privilege dropping by November 1st
2016 running Homebrew as root will be disabled. No Homebrew maintainers plan
to work on this functionality.
Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.

I do have the newest `boxen-homebrew` and run `bundle exec librarian-puppet install --path=shared --clean`:

```ruby
github "homebrew",    "2.0.2"
```

What could be the problem? Is there some cache I need to bust?
