### ISSUE TITLE
Problem installing xampp using boxen

### ISSUE THREAD

**Issue by happicamper** [boxen/our-boxen#822]
Tried installing xampp using manifest   

```
package { 'xampp':  
    ensure   => 'present',  
    provider => 'appdmg',  
    source   => 'https://www.apachefriends.org/xampp-files/7.0.8/xampp-osx-7.0.8-0-installer.dmg',  
    install_options => [  
      '--appdir=/Applications'  
    ];  
  }`  
```
results to image unrecognized, tried replacing `appdmg` into `pkgdmg` it executes Boxen smoothly but the application won't be installed at the end. Also tried simple brew cask: 
```
package { 'xampp':
    ensure => 'present',
    provider => 'brewcask',
}
```
 and results to `no tty present and no askpass`

**Comment by jacobbednarz** [comment]
Have you tried using brewcask to install this? There is a supported formulae already for this.

**Comment by happicamper** [comment]
Hello @jacobbednarz, nice to hear from you again. Yeah, I've tried installing xampp via brew cask (manually) and installed successfully, but when I'm gonna try Boxen for it, it fails and throw `no tty present` and no `askpass` error.

**Comment by jacobbednarz** [comment]
Terribly sorry on the delay - I'm slowly getting through these repositories and their existing issues.

Have you only tried using a puppet manifest? Do you get the same thing when you use hiera (a.k.a `boxen::personal::osx_apps`?

**Comment by happicamper** [comment]
No problem @jacobbednarz you have your priorities. 😄 
Yes, I've tried using hiera but no luck, still producing `==> sudo: no tty present and no askpass program specified` error.

**Comment by jacobbednarz** [comment]
This sounds like a broken formulae (https://github.com/caskroom/homebrew-cask/blob/master/Casks/xampp.rb). Perhaps have a try at correcting it in the upstream formulae repository?

**Comment by jacobbednarz** [comment]
I'm not expert but I think https://github.com/caskroom/homebrew-cask/blob/master/Casks/xampp.rb#L12 is your issue due to it trying to sudo on the command.

My recommendation would be to fork the repository and have a crack at resolving it locally using the homebrew guidelines and go from there. I suspect there is some sort of incompatibility between the two but I don't know enough about the homebrew ecosystem to say for sure.

**Comment by happicamper** [comment]
@jacobbednarz I'm gonna try your recommendation matey! Thank you for your time. 👍
