### ISSUE TITLE
Sierra: Fresh Install - Issue with bundler not finding gems 

### ISSUE THREAD

**Issue by jaredledvina** [boxen/our-boxen#827]
OS: macOS Sierra 
Fresh Install 
Xcode Command line Tools (not full install) 

Was simply following the bootstrapping section on the README, https://github.com/boxen/our-boxen/blob/master/README.md#L54 but when running boxen it'd error: 
 
```
Jareds-MacBook-Pro:repo jared$ ./script/boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
Could not find faraday-0.9.2 in any of the sources
find: bin: No such file or directory
Could not find rake-10.3.2 in any of the sources
Run `bundle install` to install missing gems.
```
```
Jareds-MacBook-Pro:repo jared$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing rake 10.3.2
Installing CFPropertyList 2.2.8
Installing addressable 2.3.8
Installing ansi 1.5.0
Installing json_pure 1.8.2
Installing hiera 1.3.4
Installing highline 1.6.21
Installing json 1.8.3 with native extensions
Installing thor 0.19.1
Installing librarian 0.1.2
Installing librarian-puppet 1.0.9
Installing multipart-post 2.0.0
Installing faraday 0.9.2
Installing sawyer 0.5.5
Installing octokit 2.7.2
Installing facter 2.4.4
Installing puppet 3.7.1
Installing boxen 2.9.0
Installing deep_merge 1.0.1
Installing diff-lcs 1.2.5
Installing metaclass 0.0.4
Installing mocha 1.1.0
Installing open4 1.3.4
Installing puppet-lint 0.3.2
Installing rspec-support 3.2.2
Installing rspec-core 3.2.3
Installing rspec-expectations 3.2.1
Installing rspec-mocks 3.2.1
Installing rspec 3.2.0
Installing rspec-puppet 1.0.1
Installing puppetlabs_spec_helper 0.4.1
Using bundler 1.10.6
Bundle complete! 12 Gemfile dependencies, 32 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into ./.bundle.
```
```
Jareds-MacBook-Pro:repo jared$ ./script/boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
...
```

From there everything worked without an issue.

**Comment by jacobbednarz** [comment]
Thanks for the report! :star:

I've seen this happen prior to the release of mac OS sierra so I don't think this is anything new however I still don't know exactly why it happens though.

**Comment by tommeier** [comment]
Yup - also getting this since updating to boxen 2.9.0 (el capitan pre-sierra)

**Comment by tommeier** [comment]
I couldn't work it out, but my state was stuffed in someway, so a full boxen nuke then rebuild on 2.8, then update to 2.9 worked flawlessly.

**Comment by happicamper** [comment]
Went from El Capitan (with boxen) to Sierra and tried the latest boxen again, works fine, but when I tried a fresh install of macOS Sierra and run `script/boxen` it produces error something like json 1.8.3 missing. Still trying some ways on how to resolve this missing gem.

**Comment by spacepants** [comment]
Hey there, so from what I understand Boxen caches all of the gems in the repo in order to make the initial bootstrap process as quick as possible. When the boxen gem was updated to 2.9.0 in #826, the Gemfile and lockfile were updated, and the older versions of boxen and faraday were removed from the cache, but the new versions weren't included.

#828 fixes this. :shipit:

**Comment by jacobbednarz** [comment]
@spacepants while the gems were missed, this is a longer standing issue and as I mentioned, has been present for a while prior to these updates.

I've merged the change to get the gems re-added however I'll need to find some time to investigate why this randomly happens with installations.
